# Generated by Django 2.1.1 on 2018-09-05 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(blank=True, max_length=100, null=True)),
                ('fatal', models.IntegerField(blank=True, default=0, null=True)),
                ('critical', models.IntegerField(blank=True, default=0, null=True)),
                ('possible_problem', models.IntegerField(blank=True, default=0, null=True)),
                ('recommendation', models.IntegerField(blank=True, default=0, null=True)),
                ('sitemap_date', models.DateField(auto_now=True)),
                ('sitemap_status', models.CharField(blank=True, max_length=30, null=True)),
                ('searchable_date', models.DateField(auto_now=True)),
                ('searchable_count', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
    ]
