# Generated by Django 2.1.1 on 2018-09-10 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_api', '0002_remove_table_sitemap_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='table',
            name='domain',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='table',
            name='searchable_count',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
