# Generated by Django 2.1.1 on 2018-09-10 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webmaster_api', '0003_auto_20180910_0805'),
    ]

    operations = [
        migrations.AddField(
            model_name='table',
            name='sitemap_url_count',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='critical',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='fatal',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='possible_problem',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='recommendation',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='table',
            name='searchable_count',
            field=models.IntegerField(default=0, null=True),
        ),
    ]
